### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by XieyilinMain** [Kobold831/DhizukuDPC#1]
Dhizuku permission has been granted.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.admin.DevicePolicyManager.isAffiliatedUser()' on a null object reference
	at h0.q.u(SourceFile:1)
	at x0.m0.j0(SourceFile:12)
	at x0.z.a(SourceFile:49)
	at t0.c.a(SourceFile:135)
	at com.afwsamples.dhizukudpc.common.preference.DpcPreference.d(SourceFile:13)
	at x0.m0.g0(SourceFile:37)
	at h0.u.C(SourceFile:65)
	at x0.m0.C(SourceFile:195)
	at c0.N.e(SourceFile:66)
	at c0.N.k(SourceFile:144)
	at c0.I.x(SourceFile:584)
	at c0.I.P(SourceFile:82)
	at c0.I.w(SourceFile:75)
	at c0.I.s(SourceFile:65)
	at c0.u.onStart(SourceFile:35)
	at k.p.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1596)
	at android.app.Activity.performStart(Activity.java:8923)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4068)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
```

**Comment by s1204IT** [comment]
Fixed https://github.com/Kobold831/DhizukuDPC/releases/tag/v9.0.12
